"""The floor, as a picture, for a Teams card.

A card cannot be clicked on by region -- an Image's selectAction is the whole
image -- so this is a MAP, not a picker: it shows where each free desk is and
what it is called, and the card's dropdown does the choosing. Tapping the image
opens it full size, which is where the labels become readable.

The room behind the desks is the same drawing the app uses
(client/public/plans/<plan_asset_key>.svg, generated by api/app/plans.py). The
desks are drawn on top here, as FloorPlan.tsx draws them on top in the app, in
the app's light-theme state colours -- so "green is free" means the same thing
in Teams as it does on a phone.

Teams renders PNG and JPEG in cards, not SVG, so the composite is rasterised
with resvg. Text needs a font on the host; the bot image installs DejaVu.
"""

from __future__ import annotations

import re
from xml.sax.saxutils import escape

import resvg_py

# client/src/styles.css, light theme. A Teams card's image has no theme of its
# own, and light reads on both Teams themes; a dark plan on a light Teams does not.
STATE_FILL = {
    "free": "#1a8a5a",
    "mine": "#1b6fe0",
    "booked": "#a3adbe",
    "assigned": "#4e5d75",
    "unavailable": "#a3adbe",
}
YOURS = STATE_FILL["mine"]

#: FloorPlan.tsx's DESK_R, so desks sit on the benches exactly as in the app.
DESK_R = 16

#: The plan's own stylesheet carries a prefers-color-scheme block. Drop it:
#: whatever resvg decides about media queries, this image is always light.
_DARK_BLOCK = re.compile(r"@media\s*\(prefers-color-scheme:\s*dark\)\s*\{(?:[^{}]*\{[^{}]*\})*[^{}]*\}")


def short_name(desk_name: str, floor_name: str) -> str:
    """"5F-N-03" on floor "5F" is labelled "N-03": the floor is in the title,
    and at this scale every character on the plan costs legibility."""
    prefix = f"{floor_name}-"
    return desk_name.removeprefix(prefix)


def compose_svg(plan_svg: str, floor: dict, states: dict[str, str]) -> str:
    """The app's plan drawing with the desks and their labels on top."""
    svg = _DARK_BLOCK.sub("", plan_svg)
    layer: list[str] = ['<g id="deskify-desks">']
    labels: list[str] = [
        '<g id="deskify-labels" font-family="DejaVu Sans, sans-serif" text-anchor="middle">'
    ]
    for r in floor["resources"]:
        if r["plan_x"] is None or r["plan_y"] is None:
            continue
        if r["kind"] != "desk":
            # The plan leaves bookable rooms unnamed because the app names
            # them from the database (api/app/plans.py). The bot does not book
            # rooms, so: a name, no state, no circle.
            labels.append(f'<text x="{r["plan_x"]}" y="{r["plan_y"] + 7}" font-size="19" '
                          f'font-weight="bold" fill="#5c6675">{escape(r["name"])}</text>')
            continue
        x, y = r["plan_x"], r["plan_y"]
        state = states.get(r["id"], "unavailable")
        layer.append(f'<circle cx="{x}" cy="{y}" r="{DESK_R}" fill="{STATE_FILL[state]}"'
                     + (' opacity="0.45"' if state == "unavailable" else "") + "/>")
        if state == "mine":
            layer.append(f'<circle cx="{x}" cy="{y}" r="{DESK_R + 7}" fill="none" '
                         f'stroke="{YOURS}" stroke-width="3" opacity="0.5"/>')
        # Only what you could pick, or your own, is named; a label on a taken
        # desk is noise on the one image whose job is to answer "which free one?".
        if state in ("free", "mine"):
            labels.append(
                f'<text x="{x}" y="{y + DESK_R + 17}" font-size="15" font-weight="bold" '
                f'fill="#2b3442">{escape(short_name(r["name"], floor["name"]))}</text>'
            )
    layer.append("</g>")
    labels.append("</g>")
    return svg.replace("</svg>", "".join(layer) + "".join(labels) + "</svg>", 1)


def render_png(plan_svg: str, floor: dict, states: dict[str, str]) -> bytes:
    return bytes(resvg_py.svg_to_bytes(
        svg_string=compose_svg(plan_svg, floor, states),
        background="#ffffff",
        sans_serif_family="DejaVu Sans",
    ))
